// Generated by scripts/generate-icon-registry.mjs. Do not edit by hand.
// Add icons by using them in content (`icon="name"`) and rebuilding.
import {
  BookOpen,
  CircleAlert,
  CircleCheck,
  Code,
  Flame,
  History,
  Rocket,
  Settings,
} from 'lucide-react';
import type { IconComponent } from '@/lib/icons';

export const ICON_REGISTRY: Record<string, IconComponent> = {
  'book-open': BookOpen,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  code: Code,
  flame: Flame,
  history: History,
  rocket: Rocket,
  settings: Settings,
};
