/**
 * Emits .shiso/openapi.generated.ts: every normalized operation from the
 * project's OpenAPI spec, with code samples and response examples highlighted
 * by Shiki at build time so no highlighter ships to the browser.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { createHighlighter, hastToHtml } from 'shiki';
import { loadApiProject } from './lib/openapi-project.mjs';

// Keep in sync with DEFAULT_CODE_THEME in src/lib/code-blocks.ts (asserted by
// tests/openapi.test.mjs).
export const DEFAULT_OPENAPI_THEME = { light: 'github-light', dark: 'github-dark' };

const EMPTY_MODULE = `// Generated by @umami/shiso. Do not edit by hand.
import type { NormalizedOperation, SchemaPage } from '@/lib/types';

export const OPENAPI_OPERATIONS: Record<string, NormalizedOperation> = {};
export const OPENAPI_SCHEMAS: Record<string, SchemaPage> = {};
`;

let highlighterPromise;

async function getHighlighter(theme) {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({ themes: [theme.light, theme.dark], langs: [] });
  }
  const highlighter = await highlighterPromise;
  // Config fragments can change themes during a refresh without restarting
  // the process. Keep the shared highlighter ready for the current theme.
  await highlighter.loadTheme(theme.light, theme.dark);
  return highlighter;
}

async function highlight(highlighter, source, lang, theme) {
  if (!highlighter.getLoadedLanguages().includes(lang)) {
    await highlighter.loadLanguage(lang);
  }

  const hast = highlighter.codeToHast(source, {
    lang,
    themes: theme,
    defaultColor: false,
  });
  const code = hast.children[0]?.children?.[0];
  const children = code?.children || [];
  const lineCount = children.filter(node => node.tagName === 'span').length;

  return { html: hastToHtml({ type: 'root', children }), lineCount };
}

async function highlightOperation(operation, highlighter, theme) {
  const samples = [];
  for (const sample of operation.samples) {
    samples.push({
      ...sample,
      ...(await highlight(highlighter, sample.source, sample.language, theme)),
    });
  }

  const responses = [];
  for (const response of operation.responses) {
    responses.push(
      response.example
        ? {
            ...response,
            exampleHtml: (await highlight(highlighter, response.example, 'json', theme)).html,
          }
        : response,
    );
  }

  const requestBody =
    operation.requestBody?.example !== undefined
      ? {
          ...operation.requestBody,
          exampleHtml: (await highlight(highlighter, operation.requestBody.example, 'json', theme))
            .html,
        }
      : operation.requestBody;

  return { ...operation, samples, responses, requestBody };
}

async function writeIfChanged(output, contents) {
  const existing = await fs.readFile(output, 'utf8').catch(() => undefined);
  if (existing === contents) return;
  await fs.mkdir(path.dirname(output), { recursive: true });
  await fs.writeFile(output, contents);
}

/** Generates the openapi data module for the project, or an empty fallback. */
export async function generateOpenApiModule({
  root,
  config,
  project: preparedProject,
  theme = {
    light: config?.styling?.codeBlocks?.theme?.light || DEFAULT_OPENAPI_THEME.light,
    dark: config?.styling?.codeBlocks?.theme?.dark || DEFAULT_OPENAPI_THEME.dark,
  },
  output,
}) {
  if (!config?.api?.spec) {
    await writeIfChanged(output, EMPTY_MODULE);
    return { operations: 0 };
  }

  const project = preparedProject ?? (await loadApiProject({ root, api: config.api }));
  const highlighter = await getHighlighter(theme);
  const operations = {};
  const schemas = {};

  // Both the bare and the spec-qualified key resolve to the same object; bare
  // keys that several specs share are omitted so pages must qualify them.
  const highlighted = new Map();
  for (const [key, operation] of project.operationsByKey) {
    if (!operation) continue;
    if (!highlighted.has(operation)) {
      highlighted.set(operation, await highlightOperation(operation, highlighter, theme));
    }
    operations[key] = highlighted.get(operation);
  }
  for (const [key, schema] of project.schemasByKey) {
    if (!schema) continue;
    if (!highlighted.has(schema)) {
      highlighted.set(
        schema,
        schema.example
          ? {
              ...schema,
              exampleHtml: (await highlight(highlighter, schema.example, 'json', theme)).html,
            }
          : schema,
      );
    }
    schemas[key] = highlighted.get(schema);
  }

  const contents = `// Generated by @umami/shiso. Do not edit by hand.
import type { NormalizedOperation, SchemaPage } from '@/lib/types';

export const OPENAPI_OPERATIONS: Record<string, NormalizedOperation> = ${JSON.stringify(operations, null, 2)};

export const OPENAPI_SCHEMAS: Record<string, SchemaPage> = ${JSON.stringify(schemas, null, 2)};
`;

  await writeIfChanged(output, contents);
  return { operations: project.operations.length, schemas: project.schemas.length };
}
